- adafruit_espatcommands.py
See if you think this is a good way to do this.
espatcommands  has an input parameter baudrate but it actually does not use it so I use it to allow you to switch the baudrate after it initializes.  At 115200 I am getting a lot of dropped characters. it works much better at 9600 baud!  We can change the baudrate of the ESP8266 or ESP32 permanetly via AT+UART_DEF but this way we can start at the 115200 default and set it if we want to.
If the input baudrate  matches the current baudrate setting, then it does not do anything so you don't have to use this.
> allow baud rate change

- examples/espatcontrol_cheerlights.py
fixes #12 
```<--- b'\r\nOK\r\n'
<--- b''
[b'']
---> AT+CIPCLOSE
<--- b'CLOSED\r\n\r\nOK\r\n'
Reply is OK!
---------------------------------------- Size:  0
----------------------------------------
IndexError processing Body, retrying
list index out of range
---> ATE0
<--- b'\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:4\r\n\r\nOK\r\n'
Retrieving data source...---> AT+CIPSTATUS
<--- b'STATUS:4\r\n\r\nOK\r\n'
---> AT+CIPSTART="TCP","api.thingspeak.com",80,10
<--- b'CONNECT\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:3\r\n+CIPSTATUS:0,"TCP","52.0.246.0",80,59857,0\r\n\r\nOK\r\n'
---> AT+CIPSEND=109
<--- b'\r\nOK\r\n'
<--- b''
Receiving: 1276
[b'HTTP/1.1 200 OK', b'Content-Type: application/json; charset=utf-8', b'Transfer-Encoding: chunked', b'Connection: close', b'Status: 200 OK', …
```
>  add try/except to cheerlights demo

- examples/espatcontrol_post.py
Adding pinout for Particle Argon boards to the `espatcontrol_post` example
> Add pinout for Particle Argon Boards to Post Example

- examples/espatcontrol_simpletest.py
- examples/espatcontrol_webclient.py
Adding pinouts for compatibly with Particle Argon boards.
Tested on Particle Argon running `Adafruit CircuitPython 4.0.0-alpha.5-53-g555da95cf`
> adding particle argon pinouts to simpletest and webclient

- examples/espatcontrol_aio_post.py
- examples/espatcontrol_cheerlights.py
- examples/espatcontrol_countviewer.py
- examples/espatcontrol_quoteEPD.py
- examples/espatcontrol_simpletest.py
- examples/espatcontrol_webclient.py
fix import in countviewer example, add ValueError to Execption trap in examples.
the imports need to be "from adafruit_espcontrol import ..."
some errors result in ValueError -- report failure but continue retrying.
>  fixup examples

- adafruit_espatcontrol/adafruit_espatcontrol_requests.py
- examples/espatcontrol_quoteEPD.py
We're renaming `ujson` to `json` in 4.0.0. Tries to import json parser as either `json` or `ujson` for upward compatibility. Renames import to `json_module` to avoid conflicts with variables named `json`.
> import either json or ujson

- adafruit_espatcontrol/adafruit_espatcontrol.py
- examples/espatcontrol_aio_post.py
- examples/espatcontrol_cheerlights.py
- examples/espatcontrol_countviewer.py
- examples/espatcontrol_quoteEPD.py
- examples/espatcontrol_secrets.py
- examples/espatcontrol_simpletest.py
- examples/espatcontrol_webclient.py
imports secret  info from secrets.py
> switch to using secrets.py

- adafruit_espatcontrol/adafruit_espatcontrol.py
- examples/espatcontrol_simpletest.py
- examples/espatcontrol_webclient.py
the ESP32 was timinng out when receiving the AP scan -- increasing timeout to 5 seconds seems to fix it. also the ESP32 seems to magically reconnect to the last AP even after a hard reset. I changed the simpletest to force an AP scan and reconnect.
Tested with 8266 on particle xenon and ESP32 on particle argon
also left initial baudrates for simpletest and webclient at default 115200 and use rts_pin.
>  increase CWLAP timeout, modify simpletest to fix AP Scan

- adafruit_espatcontrol/adafruit_espatcontrol.py
- adafruit_espatcontrol/adafruit_espatcontrol_socket.py
I know there is no longer support for ESP AT Control using UART. But this pull request fixed some bugs and tested working with Espressif AT Firmware v2.2.0.
> Fix compatibility issue with the latest adafruit_requests.py library

- adafruit_espatcontrol/adafruit_espatcontrol.py
Increased the timeout period for socket_connect() from 3 seconds to 10 seconds.
Some website especially SSL might required more than 3 seconds to be connected (eg: Telegram API).
> Increased the timeout for socket_connect().

- adafruit_espatcontrol/adafruit_espatcontrol.py
When receiving large amounts of data we would sometimes loose information here and there. By reading all available data from the uart this problem has been solved.
> Read larger chunks to avoid loosing data.

- examples/esp_atcontrol_aio_post.py
- examples/esp_atcontrol_simpletest.py
The current setup/init logic for this library is focused on the Particle Aragon.  I added a If block to the examples with the default logic being the Particle (else) and (if board.board_id == "challenger_rp2040_wifi") being for the challenger.  Should make it easier for adding other boards as well.
I moved the debug setting to a variable that is set in the early code.
For the Challenger boards I am getting some errors on AT commands not always sending back an expected OK.  Have opened issue in Adafruit_CircuitPython_ESP_ATcontrol AT+CWLAP Does not return OK #48
I have also added a few comment lines that I think will help people.  In aiocontrol_simpletest,  I added a reminder that you need to create the feed in adafruitio, and what additional entries you need in the secrets file.  In …
> Adding Support for Challenger 2040 WiFi boards. 

- examples/esp_atcontrol_aio_post.py
- examples/esp_atcontrol_cheerlights.py
- examples/esp_atcontrol_countviewer.py
- examples/esp_atcontrol_localtime.py
- examples/esp_atcontrol_simpletest.py
- examples/esp_atcontrol_webclient.py
Fixes for "in Adafruit_CircuitPython_ESP_ATcontrol AT+CWLAP Does not return OK #48".  or at least a workaround.  Buffer is defined for Challenger RP2040 WiFi Boards that keeps it from overrunning CP.
All the examples now have a if/elif for the Challenger 2040 WiFi boards, and all the examples now run!
Other small changes to add cleaner output formatting, A variable for debug level, and other small tweaks..
> Fixes for "in Adafruit_CircuitPython_ESP_ATcontrol AT+CWLAP Does not return OK #48"

- adafruit_espatcontrol/adafruit_espatcontrol.py
- adafruit_espatcontrol/adafruit_espatcontrol_socket.py
- adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py
As is, some imports were happen before the `typing` import guard in the `try`/`except` block kicked in.  This moves imports so they won't actually import.
> Swap import orders

- adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py
Allows for import of `Protocol` in Python 3.7, which has it in `typing_extensions`
> Fix import of Protocol in adafruit_espatcontrol_wifimanager.py

- adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py
- requirements.txt
- setup.py
Pins to `circuitpython_typing` minimum release that adds this functionality
> Use circuitpython_typing.FillBasedLED instead of custom Pixel protocol

- README.rst
Fixes build CI failure found while searching for libraries with failed CI results from the `.pre-commit-config.yaml` patch
> Increase depreciation header line length

- adafruit_espatcontrol/adafruit_espatcontrol.py
This PR is a fix for #58. Tested with an ESP01S and a Pico against `netcat -u -l <portnr>`:
- `socket_connect()` saves the connection type as an object attribute and fixes at_response handling
- `socket_send()` does not try to read a response (there is no response with UDP), this saves some ms
- `socket_disconnect()` resets saved connection-type
> fix UDP handling

- adafruit_espatcontrol/adafruit_espatcontrol.py
This adds the method deep_sleep(ms).
Tested with Pi Pico, see for example https://github.com/bablokb/pico-esp01.
Implements #14
> added deep_sleep()

- adafruit_espatcontrol/adafruit_espatcontrol.py
- adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py
This patch  fixes #61 by
- adding retries and timeout-parameters to all levels of the software-stack
- pushing timeout/retries from top to bottom
- executing retry-loop only from `at_response`
The number of retries can now be controlled at application-level, the user of the library can decide if she needs many retries or prefers fast failing.
The patches also gets rid of a number of loops that either never did what they should do or which were never executed anyhow.
> Consolidate retry-logic
